name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy rustfmt llvm-tools
      - run: cargo install grcov cargo-mutants just
      - run: cargo fmt --check
      - run: just clippy coverage
      - run: just mutants
